# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from error import error_box


# noinspection PyAttributeOutsideInit
class SettingsDialog(object):
    def __init__(self, main_window, menu_bar, status_bar, title_label):
        self.main_window = main_window
        self.menu_bar = menu_bar
        self.status_bar = status_bar
        self.title_label = title_label

    # noinspection PyTypeChecker
    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(721, 576)
        Dialog.setStyleSheet("#title_label{\n"
                             "text-align: center;\n"
                             "font: garamond;\n"
                             "font-size: 48 pts;\n"
                             "\n"
                             "\n"
                             "\n"
                             "}")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(40, 100, 302, 392))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.right_vert_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.right_vert_layout.setContentsMargins(0, 0, 0, 0)
        self.right_vert_layout.setObjectName("right_vert_layout")
        self.labels_vert_layout = QtWidgets.QVBoxLayout()
        self.labels_vert_layout.setObjectName("labels_vert_layout")
        self.labels_font_hor_layout = QtWidgets.QHBoxLayout()
        self.labels_font_hor_layout.setObjectName("labels_font_hor_layout")
        self.labels_font_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labels_font_label.setFont(font)
        self.labels_font_label.setObjectName("labels_font_label")
        self.labels_font_hor_layout.addWidget(self.labels_font_label)
        self.labels_font_comboBox = QtWidgets.QFontComboBox(self.verticalLayoutWidget_8)
        self.labels_font_comboBox.setObjectName("labels_font_comboBox")
        self.labels_font_hor_layout.addWidget(self.labels_font_comboBox)
        self.labels_vert_layout.addLayout(self.labels_font_hor_layout)
        self.labels_color_hor_layout = QtWidgets.QHBoxLayout()
        self.labels_color_hor_layout.setObjectName("labels_color_hor_layout")
        self.labels_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labels_color_label.setFont(font)
        self.labels_color_label.setObjectName("labels_color_label")
        self.labels_color_hor_layout.addWidget(self.labels_color_label)
        self.labels_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.labels_color_comboBox.setObjectName("labels_color_comboBox")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_comboBox.addItem("")
        self.labels_color_hor_layout.addWidget(self.labels_color_comboBox)
        self.labels_vert_layout.addLayout(self.labels_color_hor_layout)
        self.labels_font_color_hor_layout = QtWidgets.QHBoxLayout()
        self.labels_font_color_hor_layout.setObjectName("labels_font_color_hor_layout")
        self.labels_font_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labels_font_color_label.setFont(font)
        self.labels_font_color_label.setObjectName("labels_font_color_label")
        self.labels_font_color_hor_layout.addWidget(self.labels_font_color_label)
        self.labels_font_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.labels_font_color_comboBox.setObjectName("labels_font_color_comboBox")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_comboBox.addItem("")
        self.labels_font_color_hor_layout.addWidget(self.labels_font_color_comboBox)
        self.labels_vert_layout.addLayout(self.labels_font_color_hor_layout)
        self.right_vert_layout.addLayout(self.labels_vert_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.right_vert_layout.addItem(spacerItem)
        self.title_vert_layout = QtWidgets.QVBoxLayout()
        self.title_vert_layout.setObjectName("title_vert_layout")
        self.title_font_hor_layout = QtWidgets.QHBoxLayout()
        self.title_font_hor_layout.setObjectName("title_font_hor_layout")
        self.title_font_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_font_label.setFont(font)
        self.title_font_label.setObjectName("title_font_label")
        self.title_font_hor_layout.addWidget(self.title_font_label)
        self.title_font_comboBox = QtWidgets.QFontComboBox(self.verticalLayoutWidget_8)
        self.title_font_comboBox.setObjectName("title_font_comboBox")
        self.title_font_hor_layout.addWidget(self.title_font_comboBox)
        self.title_vert_layout.addLayout(self.title_font_hor_layout)
        self.title_color_hor_layout = QtWidgets.QHBoxLayout()
        self.title_color_hor_layout.setObjectName("title_color_hor_layout")
        self.title_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_color_label.setFont(font)
        self.title_color_label.setObjectName("title_color_label")
        self.title_color_hor_layout.addWidget(self.title_color_label)
        self.title_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.title_color_comboBox.setObjectName("title_color_comboBox")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_comboBox.addItem("")
        self.title_color_hor_layout.addWidget(self.title_color_comboBox)
        self.title_vert_layout.addLayout(self.title_color_hor_layout)
        self.title_font_color_hor_layout = QtWidgets.QHBoxLayout()
        self.title_font_color_hor_layout.setObjectName("title_font_color_hor_layout")
        self.title_font_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_font_color_label.setFont(font)
        self.title_font_color_label.setObjectName("title_font_color_label")
        self.title_font_color_hor_layout.addWidget(self.title_font_color_label)
        self.title_font_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.title_font_color_comboBox.setObjectName("title_font_color_comboBox")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_comboBox.addItem("")
        self.title_font_color_hor_layout.addWidget(self.title_font_color_comboBox)
        self.title_vert_layout.addLayout(self.title_font_color_hor_layout)
        self.right_vert_layout.addLayout(self.title_vert_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.right_vert_layout.addItem(spacerItem1)
        self.menubar_vert_layout = QtWidgets.QVBoxLayout()
        self.menubar_vert_layout.setObjectName("menubar_vert_layout")
        self.menubar_font_hor_layout = QtWidgets.QHBoxLayout()
        self.menubar_font_hor_layout.setObjectName("menubar_font_hor_layout")
        self.menubar_font_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar_font_label.setFont(font)
        self.menubar_font_label.setObjectName("menubar_font_label")
        self.menubar_font_hor_layout.addWidget(self.menubar_font_label)
        self.menubar_font_comboBox = QtWidgets.QFontComboBox(self.verticalLayoutWidget_8)
        self.menubar_font_comboBox.setObjectName("menubar_font_comboBox")
        self.menubar_font_hor_layout.addWidget(self.menubar_font_comboBox)
        self.menubar_vert_layout.addLayout(self.menubar_font_hor_layout)
        self.menubar_color_hor_layout = QtWidgets.QHBoxLayout()
        self.menubar_color_hor_layout.setObjectName("menubar_color_hor_layout")
        self.menubar_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar_color_label.setFont(font)
        self.menubar_color_label.setObjectName("menubar_color_label")
        self.menubar_color_hor_layout.addWidget(self.menubar_color_label)
        self.menubar_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.menubar_color_comboBox.setObjectName("menubar_color_comboBox")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_comboBox.addItem("")
        self.menubar_color_hor_layout.addWidget(self.menubar_color_comboBox)
        self.menubar_vert_layout.addLayout(self.menubar_color_hor_layout)
        self.menubar_font_color_hor_layout = QtWidgets.QHBoxLayout()
        self.menubar_font_color_hor_layout.setObjectName("menubar_font_color_hor_layout")
        self.menubar_font_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar_font_color_label.setFont(font)
        self.menubar_font_color_label.setObjectName("menubar_font_color_label")
        self.menubar_font_color_hor_layout.addWidget(self.menubar_font_color_label)
        self.menubar_font_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.menubar_font_color_comboBox.setObjectName("menubar_font_color_comboBox")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_comboBox.addItem("")
        self.menubar_font_color_hor_layout.addWidget(self.menubar_font_color_comboBox)
        self.menubar_vert_layout.addLayout(self.menubar_font_color_hor_layout)
        self.right_vert_layout.addLayout(self.menubar_vert_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.right_vert_layout.addItem(spacerItem2)
        self.statusbar_vert_layout = QtWidgets.QVBoxLayout()
        self.statusbar_vert_layout.setObjectName("statusbar_vert_layout")
        self.statusbar_font_hor_layout = QtWidgets.QHBoxLayout()
        self.statusbar_font_hor_layout.setObjectName("statusbar_font_hor_layout")
        self.statusbar_font_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusbar_font_label.setFont(font)
        self.statusbar_font_label.setObjectName("statusbar_font_label")
        self.statusbar_font_hor_layout.addWidget(self.statusbar_font_label)
        self.statusbar_font_comboBox = QtWidgets.QFontComboBox(self.verticalLayoutWidget_8)
        self.statusbar_font_comboBox.setObjectName("statusbar_font_comboBox")
        self.statusbar_font_hor_layout.addWidget(self.statusbar_font_comboBox)
        self.statusbar_vert_layout.addLayout(self.statusbar_font_hor_layout)
        self.statusbar_color_hor_layout = QtWidgets.QHBoxLayout()
        self.statusbar_color_hor_layout.setObjectName("statusbar_color_hor_layout")
        self.statusbar_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusbar_color_label.setFont(font)
        self.statusbar_color_label.setObjectName("statusbar_color_label")
        self.statusbar_color_hor_layout.addWidget(self.statusbar_color_label)
        self.statusbar_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.statusbar_color_comboBox.setObjectName("statusbar_color_comboBox")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_comboBox.addItem("")
        self.statusbar_color_hor_layout.addWidget(self.statusbar_color_comboBox)
        self.statusbar_vert_layout.addLayout(self.statusbar_color_hor_layout)
        self.statusbar_font_color_hor_layout = QtWidgets.QHBoxLayout()
        self.statusbar_font_color_hor_layout.setObjectName("statusbar_font_color_hor_layout")
        self.statusbar_font_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusbar_font_color_label.setFont(font)
        self.statusbar_font_color_label.setObjectName("statusbar_font_color_label")
        self.statusbar_font_color_hor_layout.addWidget(self.statusbar_font_color_label)
        self.statusbar_font_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.statusbar_font_color_comboBox.setObjectName("statusbar_font_color_comboBox")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_comboBox.addItem("")
        self.statusbar_font_color_hor_layout.addWidget(self.statusbar_font_color_comboBox)
        self.statusbar_vert_layout.addLayout(self.statusbar_font_color_hor_layout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.statusbar_vert_layout.addItem(spacerItem3)
        self.background_color_hor_layout = QtWidgets.QHBoxLayout()
        self.background_color_hor_layout.setObjectName("background_color_hor_layout")
        self.background_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.background_color_label.setFont(font)
        self.background_color_label.setObjectName("background_color_label")
        self.background_color_hor_layout.addWidget(self.background_color_label)
        self.background_color_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.background_color_comboBox.setObjectName("background_color_comboBox")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_comboBox.addItem("")
        self.background_color_hor_layout.addWidget(self.background_color_comboBox)
        self.statusbar_vert_layout.addLayout(self.background_color_hor_layout)
        self.right_vert_layout.addLayout(self.statusbar_vert_layout)
        self.left_vert_frame = QtWidgets.QFrame(Dialog)
        self.left_vert_frame.setGeometry(QtCore.QRect(350, 92, 339, 301))
        self.left_vert_frame.setObjectName("left_vert_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.left_vert_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button_vert_layout = QtWidgets.QVBoxLayout()
        self.button_vert_layout.setObjectName("button_vert_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_color_label_2 = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_color_label_2.setFont(font)
        self.button_color_label_2.setObjectName("button_color_label_2")
        self.horizontalLayout.addWidget(self.button_color_label_2)
        self.button_font_comboBox = QtWidgets.QFontComboBox(self.left_vert_frame)
        self.button_font_comboBox.setObjectName("button_font_comboBox")
        self.horizontalLayout.addWidget(self.button_font_comboBox)
        self.button_vert_layout.addLayout(self.horizontalLayout)
        self.button_color_hor_layout = QtWidgets.QHBoxLayout()
        self.button_color_hor_layout.setObjectName("button_color_hor_layout")
        self.button_color_label = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_color_label.setFont(font)
        self.button_color_label.setObjectName("button_color_label")
        self.button_color_hor_layout.addWidget(self.button_color_label)
        self.button_color_comboBox = QtWidgets.QComboBox(self.left_vert_frame)
        self.button_color_comboBox.setObjectName("button_color_comboBox")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_comboBox.addItem("")
        self.button_color_hor_layout.addWidget(self.button_color_comboBox)
        self.button_vert_layout.addLayout(self.button_color_hor_layout)
        self.button_radius_hor_layout = QtWidgets.QHBoxLayout()
        self.button_radius_hor_layout.setObjectName("button_radius_hor_layout")
        self.button_radius_comboBox = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_radius_comboBox.setFont(font)
        self.button_radius_comboBox.setObjectName("button_radius_comboBox")
        self.button_radius_hor_layout.addWidget(self.button_radius_comboBox)
        self.button_radius_comboBox_2 = QtWidgets.QComboBox(self.left_vert_frame)
        self.button_radius_comboBox_2.setObjectName("button_radius_comboBox_2")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_comboBox_2.addItem("")
        self.button_radius_hor_layout.addWidget(self.button_radius_comboBox_2)
        self.button_vert_layout.addLayout(self.button_radius_hor_layout)
        self.button_font_color_hor_layout = QtWidgets.QHBoxLayout()
        self.button_font_color_hor_layout.setObjectName("button_font_color_hor_layout")
        self.button_font_color_comboBox = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_font_color_comboBox.setFont(font)
        self.button_font_color_comboBox.setObjectName("button_font_color_comboBox")
        self.button_font_color_hor_layout.addWidget(self.button_font_color_comboBox)
        self.button_font_color_comboBox_2 = QtWidgets.QComboBox(self.left_vert_frame)
        self.button_font_color_comboBox_2.setObjectName("button_font_color_comboBox_2")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_comboBox_2.addItem("")
        self.button_font_color_hor_layout.addWidget(self.button_font_color_comboBox_2)
        self.button_vert_layout.addLayout(self.button_font_color_hor_layout)
        self.verticalLayout_10.addLayout(self.button_vert_layout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.inputbox_vert_layout = QtWidgets.QVBoxLayout()
        self.inputbox_vert_layout.setObjectName("inputbox_vert_layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_color_label_3 = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_color_label_3.setFont(font)
        self.button_color_label_3.setObjectName("button_color_label_3")
        self.horizontalLayout_2.addWidget(self.button_color_label_3)
        self.inputbox_font_comboBox = QtWidgets.QFontComboBox(self.left_vert_frame)
        self.inputbox_font_comboBox.setObjectName("inputbox_font_comboBox")
        self.horizontalLayout_2.addWidget(self.inputbox_font_comboBox)
        self.inputbox_vert_layout.addLayout(self.horizontalLayout_2)
        self.inputbox_color_hor_layout = QtWidgets.QHBoxLayout()
        self.inputbox_color_hor_layout.setObjectName("inputbox_color_hor_layout")
        self.inputbox_color_comboBox = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputbox_color_comboBox.setFont(font)
        self.inputbox_color_comboBox.setObjectName("inputbox_color_comboBox")
        self.inputbox_color_hor_layout.addWidget(self.inputbox_color_comboBox)
        self.inputbox_color_comboBox_2 = QtWidgets.QComboBox(self.left_vert_frame)
        self.inputbox_color_comboBox_2.setObjectName("inputbox_color_comboBox_2")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_comboBox_2.addItem("")
        self.inputbox_color_hor_layout.addWidget(self.inputbox_color_comboBox_2)
        self.inputbox_vert_layout.addLayout(self.inputbox_color_hor_layout)
        self.inputbox_radius_hor_layout = QtWidgets.QHBoxLayout()
        self.inputbox_radius_hor_layout.setObjectName("inputbox_radius_hor_layout")
        self.inputbox_radius_label = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputbox_radius_label.setFont(font)
        self.inputbox_radius_label.setObjectName("inputbox_radius_label")
        self.inputbox_radius_hor_layout.addWidget(self.inputbox_radius_label)
        self.inputbox_radius_comboBox = QtWidgets.QComboBox(self.left_vert_frame)
        self.inputbox_radius_comboBox.setObjectName("inputbox_radius_comboBox")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_comboBox.addItem("")
        self.inputbox_radius_hor_layout.addWidget(self.inputbox_radius_comboBox)
        self.inputbox_vert_layout.addLayout(self.inputbox_radius_hor_layout)
        self.inputbox_font_color_hor_layout = QtWidgets.QHBoxLayout()
        self.inputbox_font_color_hor_layout.setObjectName("inputbox_font_color_hor_layout")
        self.inputbox_font_color_label = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputbox_font_color_label.setFont(font)
        self.inputbox_font_color_label.setObjectName("inputbox_font_color_label")
        self.inputbox_font_color_hor_layout.addWidget(self.inputbox_font_color_label)
        self.inputbox_font_color_comboBox = QtWidgets.QComboBox(self.left_vert_frame)
        self.inputbox_font_color_comboBox.setObjectName("inputbox_font_color_comboBox")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_comboBox.addItem("")
        self.inputbox_font_color_hor_layout.addWidget(self.inputbox_font_color_comboBox)
        self.inputbox_vert_layout.addLayout(self.inputbox_font_color_hor_layout)
        self.verticalLayout_10.addLayout(self.inputbox_vert_layout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.combobox_vert_layout = QtWidgets.QVBoxLayout()
        self.combobox_vert_layout.setObjectName("combobox_vert_layout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_color_label_4 = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_color_label_4.setFont(font)
        self.button_color_label_4.setObjectName("button_color_label_4")
        self.horizontalLayout_3.addWidget(self.button_color_label_4)
        self.combobox_font_comboBox = QtWidgets.QFontComboBox(self.left_vert_frame)
        self.combobox_font_comboBox.setObjectName("combobox_font_comboBox")
        self.horizontalLayout_3.addWidget(self.combobox_font_comboBox)
        self.combobox_vert_layout.addLayout(self.horizontalLayout_3)
        self.combobox_color_hor_layout = QtWidgets.QHBoxLayout()
        self.combobox_color_hor_layout.setObjectName("combobox_color_hor_layout")
        self.combobox_color_label = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_color_label.setFont(font)
        self.combobox_color_label.setObjectName("combobox_color_label")
        self.combobox_color_hor_layout.addWidget(self.combobox_color_label)
        self.combobox_color_comboBox = QtWidgets.QComboBox(self.left_vert_frame)
        self.combobox_color_comboBox.setObjectName("combobox_color_comboBox")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_comboBox.addItem("")
        self.combobox_color_hor_layout.addWidget(self.combobox_color_comboBox)
        self.combobox_vert_layout.addLayout(self.combobox_color_hor_layout)
        self.combobox_radius_hor_layout = QtWidgets.QHBoxLayout()
        self.combobox_radius_hor_layout.setObjectName("combobox_radius_hor_layout")
        self.combobox_radius_label = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_radius_label.setFont(font)
        self.combobox_radius_label.setObjectName("combobox_radius_label")
        self.combobox_radius_hor_layout.addWidget(self.combobox_radius_label)
        self.combobox_radius_comboBox = QtWidgets.QComboBox(self.left_vert_frame)
        self.combobox_radius_comboBox.setObjectName("combobox_radius_comboBox")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_comboBox.addItem("")
        self.combobox_radius_hor_layout.addWidget(self.combobox_radius_comboBox)
        self.combobox_vert_layout.addLayout(self.combobox_radius_hor_layout)
        self.combobox_font_color_hor_layout = QtWidgets.QHBoxLayout()
        self.combobox_font_color_hor_layout.setObjectName("combobox_font_color_hor_layout")
        self.combobox_font_color_label = QtWidgets.QLabel(self.left_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combobox_font_color_label.setFont(font)
        self.combobox_font_color_label.setObjectName("combobox_font_color_label")
        self.combobox_font_color_hor_layout.addWidget(self.combobox_font_color_label)
        self.combobox_font_color_comboBox = QtWidgets.QComboBox(self.left_vert_frame)
        self.combobox_font_color_comboBox.setObjectName("combobox_font_color_comboBox")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_comboBox.addItem("")
        self.combobox_font_color_hor_layout.addWidget(self.combobox_font_color_comboBox)
        self.combobox_vert_layout.addLayout(self.combobox_font_color_hor_layout)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_27.addItem(spacerItem6)
        self.combobox_vert_layout.addLayout(self.horizontalLayout_27)
        self.verticalLayout_10.addLayout(self.combobox_vert_layout)
        self.theme_vert_frame = QtWidgets.QFrame(Dialog)
        self.theme_vert_frame.setGeometry(QtCore.QRect(460, 402, 221, 108))
        self.theme_vert_frame.setObjectName("theme_vert_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.theme_vert_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_theme_hor_layout = QtWidgets.QHBoxLayout()
        self.new_theme_hor_layout.setObjectName("new_theme_hor_layout")
        self.theme_name_label = QtWidgets.QLabel(self.theme_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.theme_name_label.setFont(font)
        self.theme_name_label.setObjectName("theme_name_label")
        self.new_theme_hor_layout.addWidget(self.theme_name_label)
        self.theme_name_lineEdit = QtWidgets.QLineEdit(self.theme_vert_frame)
        self.theme_name_lineEdit.setObjectName("theme_name_lineEdit")
        self.new_theme_hor_layout.addWidget(self.theme_name_lineEdit)
        self.verticalLayout.addLayout(self.new_theme_hor_layout)
        self.saved_theme_hor_layout = QtWidgets.QHBoxLayout()
        self.saved_theme_hor_layout.setObjectName("saved_theme_hor_layout")
        self.saved_themes_label = QtWidgets.QLabel(self.theme_vert_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saved_themes_label.setFont(font)
        self.saved_themes_label.setObjectName("saved_themes_label")
        self.saved_theme_hor_layout.addWidget(self.saved_themes_label)
        self.saved_themes_comboBox = QtWidgets.QComboBox(self.theme_vert_frame)
        self.saved_themes_comboBox.setObjectName("saved_themes_comboBox")
        self.saved_theme_hor_layout.addWidget(self.saved_themes_comboBox)
        self.verticalLayout.addLayout(self.saved_theme_hor_layout)
        self.themes_buttons_hor_layout = QtWidgets.QHBoxLayout()
        self.themes_buttons_hor_layout.setObjectName("themes_buttons_hor_layout")
        self.save_pushButton = QtWidgets.QPushButton(self.theme_vert_frame)
        self.save_pushButton.setAutoDefault(False)
        self.save_pushButton.setObjectName("save_pushButton")
        self.themes_buttons_hor_layout.addWidget(self.save_pushButton)
        self.load_pushButton = QtWidgets.QPushButton(self.theme_vert_frame)
        self.load_pushButton.setAutoDefault(False)
        self.load_pushButton.setObjectName("load_pushButton")
        self.themes_buttons_hor_layout.addWidget(self.load_pushButton)
        self.verticalLayout.addLayout(self.themes_buttons_hor_layout)
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(0, 0, 731, 80))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.title_hor_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.title_hor_layout.setContentsMargins(0, 0, 0, 0)
        self.title_hor_layout.setObjectName("title_hor_layout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_hor_layout.addItem(spacerItem7)
        self.title_label = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("")
        self.title_label.setObjectName("title_label")
        self.title_hor_layout.addWidget(self.title_label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_hor_layout.addItem(spacerItem8)
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(2, 500, 731, 80))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.bottom_hor_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.bottom_hor_layout.setContentsMargins(0, 0, 0, 0)
        self.bottom_hor_layout.setObjectName("bottom_hor_layout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_hor_layout.addItem(spacerItem9)
        self.bot_buttons_hor_layout = QtWidgets.QHBoxLayout()
        self.bot_buttons_hor_layout.setObjectName("bot_buttons_hor_layout")
        self.ok_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.bot_buttons_hor_layout.addWidget(self.ok_pushButton)
        self.apply_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.apply_pushButton.setStyleSheet("")
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.bot_buttons_hor_layout.addWidget(self.apply_pushButton)
        self.defaults_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.defaults_pushButton.setObjectName("defaults_pushButton")
        self.bot_buttons_hor_layout.addWidget(self.defaults_pushButton)
        self.bottom_hor_layout.addLayout(self.bot_buttons_hor_layout)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_hor_layout.addItem(spacerItem10)

        self.activate_theme_pushButton = QtWidgets.QPushButton(self.theme_vert_frame)
        self.activate_theme_pushButton.setAutoDefault(False)
        self.activate_theme_pushButton.setObjectName("activate_theme_pushButton")
        self.themes_buttons_hor_layout.addWidget(self.activate_theme_pushButton)

        self.connect = sqlite3.connect('ebook.db')
        self.cursor = self.connect.cursor()

        self.apply_pushButton.clicked.connect(lambda: self.apply_style())
        self.save_pushButton.clicked.connect(lambda: self.save_style())
        self.ok_pushButton.clicked.connect(lambda: self.ok_apply_style())
        self.load_pushButton.clicked.connect(lambda: self.load_style())
        self.activate_theme_pushButton.clicked.connect(lambda: self.activate_theme())
        self.defaults_pushButton.clicked.connect(
            lambda: self.saved_themes_comboBox.setCurrentText("Default"))
        self.defaults_pushButton.clicked.connect(lambda: self.apply_style())
        self.saved_themes_comboBox.removeItem(0)
        self.saved_themes_comboBox.insertItem(0, "")
        self.saved_themes_comboBox.removeItem(1)
        self.saved_themes_comboBox.insertItem(1, "Default")
        self.refresh_themes()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labels_font_label.setText(_translate("Dialog", "Labels Font"))
        self.labels_color_label.setText(_translate("Dialog", "Labels Color"))
        self.labels_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.labels_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.labels_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.labels_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.labels_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.labels_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.labels_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.labels_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.labels_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.labels_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.labels_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.labels_font_color_label.setText(_translate("Dialog", "Labels Font Color"))
        self.labels_font_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.labels_font_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.labels_font_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.labels_font_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.labels_font_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.labels_font_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.labels_font_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.labels_font_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.labels_font_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.labels_font_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.labels_font_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.title_font_label.setText(_translate("Dialog", "Title Font"))
        self.title_color_label.setText(_translate("Dialog", "Title Color"))
        self.title_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.title_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.title_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.title_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.title_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.title_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.title_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.title_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.title_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.title_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.title_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.title_font_color_label.setText(_translate("Dialog", "Title Font Color"))
        self.title_font_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.title_font_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.title_font_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.title_font_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.title_font_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.title_font_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.title_font_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.title_font_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.title_font_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.title_font_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.title_font_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.menubar_font_label.setText(_translate("Dialog", "MenuBar Font"))
        self.menubar_color_label.setText(_translate("Dialog", "MenuBar Color"))
        self.menubar_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.menubar_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.menubar_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.menubar_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.menubar_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.menubar_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.menubar_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.menubar_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.menubar_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.menubar_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.menubar_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.menubar_color_comboBox.setItemText(11, _translate("Dialog", "Light Grey"))
        self.menubar_font_color_label.setText(_translate("Dialog", "MenuBar Font Color"))
        self.menubar_font_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.menubar_font_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.menubar_font_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.menubar_font_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.menubar_font_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.menubar_font_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.menubar_font_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.menubar_font_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.menubar_font_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.menubar_font_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.menubar_font_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.statusbar_font_label.setText(_translate("Dialog", "StatusBar Font"))
        self.statusbar_color_label.setText(_translate("Dialog", "StatusBar Color"))
        self.statusbar_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.statusbar_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.statusbar_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.statusbar_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.statusbar_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.statusbar_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.statusbar_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.statusbar_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.statusbar_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.statusbar_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.statusbar_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.statusbar_color_comboBox.setItemText(11, _translate("Dialog", "Light Grey"))
        self.statusbar_font_color_label.setText(_translate("Dialog", "StatusBar Font Color"))
        self.statusbar_font_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.statusbar_font_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.statusbar_font_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.statusbar_font_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.statusbar_font_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.statusbar_font_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.statusbar_font_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.statusbar_font_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.statusbar_font_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.statusbar_font_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.statusbar_font_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.background_color_label.setText(_translate("Dialog", "Background Color"))
        self.background_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.background_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.background_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.background_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.background_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.background_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.background_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.background_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.background_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.background_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.background_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.button_color_label_2.setText(_translate("Dialog", "Button Font"))
        self.button_color_label.setText(_translate("Dialog", "Button Color"))
        self.button_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.button_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.button_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.button_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.button_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.button_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.button_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.button_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.button_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.button_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.button_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.button_radius_comboBox.setText(_translate("Dialog", "Button Radius"))
        self.button_radius_comboBox_2.setItemText(0, _translate("Dialog", "0"))
        self.button_radius_comboBox_2.setItemText(1, _translate("Dialog", "1"))
        self.button_radius_comboBox_2.setItemText(2, _translate("Dialog", "2"))
        self.button_radius_comboBox_2.setItemText(3, _translate("Dialog", "3"))
        self.button_radius_comboBox_2.setItemText(4, _translate("Dialog", "4"))
        self.button_radius_comboBox_2.setItemText(5, _translate("Dialog", "5"))
        self.button_radius_comboBox_2.setItemText(6, _translate("Dialog", "6"))
        self.button_radius_comboBox_2.setItemText(7, _translate("Dialog", "7"))
        self.button_radius_comboBox_2.setItemText(8, _translate("Dialog", "8"))
        self.button_radius_comboBox_2.setItemText(9, _translate("Dialog", "9"))
        self.button_radius_comboBox_2.setItemText(10, _translate("Dialog", "10"))
        self.button_radius_comboBox_2.setItemText(11, _translate("Dialog", "11"))
        self.button_radius_comboBox_2.setItemText(12, _translate("Dialog", "12"))
        self.button_radius_comboBox_2.setItemText(13, _translate("Dialog", "13"))
        self.button_radius_comboBox_2.setItemText(14, _translate("Dialog", "14"))
        self.button_font_color_comboBox.setText(_translate("Dialog", "Button Font Color"))
        self.button_font_color_comboBox_2.setItemText(0, _translate("Dialog", "Black "))
        self.button_font_color_comboBox_2.setItemText(1, _translate("Dialog", "Red"))
        self.button_font_color_comboBox_2.setItemText(2, _translate("Dialog", "Orange"))
        self.button_font_color_comboBox_2.setItemText(3, _translate("Dialog", "Yellow"))
        self.button_font_color_comboBox_2.setItemText(4, _translate("Dialog", "Green"))
        self.button_font_color_comboBox_2.setItemText(5, _translate("Dialog", "Blue"))
        self.button_font_color_comboBox_2.setItemText(6, _translate("Dialog", "Purple"))
        self.button_font_color_comboBox_2.setItemText(7, _translate("Dialog", "Pink"))
        self.button_font_color_comboBox_2.setItemText(8, _translate("Dialog", "Brown"))
        self.button_font_color_comboBox_2.setItemText(9, _translate("Dialog", "Grey"))
        self.button_font_color_comboBox_2.setItemText(10, _translate("Dialog", "White"))
        self.button_color_label_3.setText(_translate("Dialog", "InputBox Font"))
        self.inputbox_color_comboBox.setText(_translate("Dialog", "InputBox Color"))
        self.inputbox_color_comboBox_2.setItemText(0, _translate("Dialog", "Black "))
        self.inputbox_color_comboBox_2.setItemText(1, _translate("Dialog", "Red"))
        self.inputbox_color_comboBox_2.setItemText(2, _translate("Dialog", "Orange"))
        self.inputbox_color_comboBox_2.setItemText(3, _translate("Dialog", "Yellow"))
        self.inputbox_color_comboBox_2.setItemText(4, _translate("Dialog", "Green"))
        self.inputbox_color_comboBox_2.setItemText(5, _translate("Dialog", "Blue"))
        self.inputbox_color_comboBox_2.setItemText(6, _translate("Dialog", "Purple"))
        self.inputbox_color_comboBox_2.setItemText(7, _translate("Dialog", "Pink"))
        self.inputbox_color_comboBox_2.setItemText(8, _translate("Dialog", "Brown"))
        self.inputbox_color_comboBox_2.setItemText(9, _translate("Dialog", "Grey"))
        self.inputbox_color_comboBox_2.setItemText(10, _translate("Dialog", "White"))
        self.inputbox_radius_label.setText(_translate("Dialog", "InputBox Radius"))
        self.inputbox_radius_comboBox.setItemText(0, _translate("Dialog", "0"))
        self.inputbox_radius_comboBox.setItemText(1, _translate("Dialog", "1"))
        self.inputbox_radius_comboBox.setItemText(2, _translate("Dialog", "2"))
        self.inputbox_radius_comboBox.setItemText(3, _translate("Dialog", "3"))
        self.inputbox_radius_comboBox.setItemText(4, _translate("Dialog", "4"))
        self.inputbox_radius_comboBox.setItemText(5, _translate("Dialog", "5"))
        self.inputbox_radius_comboBox.setItemText(6, _translate("Dialog", "6"))
        self.inputbox_radius_comboBox.setItemText(7, _translate("Dialog", "7"))
        self.inputbox_radius_comboBox.setItemText(8, _translate("Dialog", "8"))
        self.inputbox_font_color_label.setText(_translate("Dialog", "InputBox Font Color"))
        self.inputbox_font_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.inputbox_font_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.inputbox_font_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.inputbox_font_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.inputbox_font_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.inputbox_font_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.inputbox_font_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.inputbox_font_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.inputbox_font_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.inputbox_font_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.inputbox_font_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.button_color_label_4.setText(_translate("Dialog", "ComboBox Font"))
        self.combobox_color_label.setText(_translate("Dialog", "ComboBox Color"))
        self.combobox_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.combobox_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.combobox_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.combobox_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.combobox_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.combobox_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.combobox_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.combobox_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.combobox_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.combobox_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.combobox_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.combobox_color_comboBox.setItemText(11, _translate("Dialog", "Light Grey"))
        self.combobox_radius_label.setText(_translate("Dialog", "ComboBox Radius"))
        self.combobox_radius_comboBox.setItemText(0, _translate("Dialog", "0"))
        self.combobox_radius_comboBox.setItemText(1, _translate("Dialog", "1"))
        self.combobox_radius_comboBox.setItemText(2, _translate("Dialog", "2"))
        self.combobox_radius_comboBox.setItemText(3, _translate("Dialog", "3"))
        self.combobox_radius_comboBox.setItemText(4, _translate("Dialog", "4"))
        self.combobox_radius_comboBox.setItemText(5, _translate("Dialog", "5"))
        self.combobox_radius_comboBox.setItemText(6, _translate("Dialog", "6"))
        self.combobox_radius_comboBox.setItemText(7, _translate("Dialog", "7"))
        self.combobox_radius_comboBox.setItemText(8, _translate("Dialog", "8"))
        self.combobox_font_color_label.setText(_translate("Dialog", "ComboBox Font Color"))
        self.combobox_font_color_comboBox.setItemText(0, _translate("Dialog", "Black "))
        self.combobox_font_color_comboBox.setItemText(1, _translate("Dialog", "Red"))
        self.combobox_font_color_comboBox.setItemText(2, _translate("Dialog", "Orange"))
        self.combobox_font_color_comboBox.setItemText(3, _translate("Dialog", "Yellow"))
        self.combobox_font_color_comboBox.setItemText(4, _translate("Dialog", "Green"))
        self.combobox_font_color_comboBox.setItemText(5, _translate("Dialog", "Blue"))
        self.combobox_font_color_comboBox.setItemText(6, _translate("Dialog", "Purple"))
        self.combobox_font_color_comboBox.setItemText(7, _translate("Dialog", "Pink"))
        self.combobox_font_color_comboBox.setItemText(8, _translate("Dialog", "Brown"))
        self.combobox_font_color_comboBox.setItemText(9, _translate("Dialog", "Grey"))
        self.combobox_font_color_comboBox.setItemText(10, _translate("Dialog", "White"))
        self.theme_name_label.setText(_translate("Dialog", "Theme Name"))
        self.saved_themes_label.setText(_translate("Dialog", "Saved Themes"))
        self.save_pushButton.setText(_translate("Dialog", "Save"))
        self.load_pushButton.setText(_translate("Dialog", "Load"))
        self.activate_theme_pushButton.setText(_translate("Dialog", "Activate"))
        self.title_label.setText(_translate("Dialog", "Application Settings"))
        self.ok_pushButton.setText(_translate("Dialog", "OK"))
        self.apply_pushButton.setText(_translate("Dialog", "Apply"))
        self.defaults_pushButton.setText(_translate("Dialog", "Defaults"))

    def refresh_themes(self):
        with self.connect:
            self.cursor.execute("SELECT name FROM settings")
            themes = self.cursor.fetchall()
            for theme in themes:
                self.saved_themes_comboBox.addItem(theme[0])

    def activate_theme(self):
        theme_name = self.saved_themes_comboBox.currentText()
        with self.connect:
            self.cursor.execute("UPDATE settings SET active=0 WHERE active=1")
            self.cursor.execute("UPDATE settings SET active=1 WHERE name=?", (theme_name,))
        self.load_style()
        self.apply_style()

    def load_style(self):
        theme_name = self.saved_themes_comboBox.currentText()
        with self.connect:
            self.cursor.execute("SELECT * FROM settings WHERE name=?", (theme_name,))
            theme = self.cursor.fetchone()
        if theme is None:
            return 0
        else:
            self.labels_font_comboBox.setCurrentText(theme[1])
            self.labels_color_comboBox.setCurrentText(theme[2])
            self.labels_font_color_comboBox.setCurrentText(theme[3])
            self.title_font_comboBox.setCurrentText(theme[4])
            self.title_color_comboBox.setCurrentText(theme[5])
            self.title_font_color_comboBox.setCurrentText(theme[6])
            self.menubar_font_comboBox.setCurrentText(theme[7])
            self.menubar_color_comboBox.setCurrentText(theme[8])
            self.menubar_font_color_comboBox.setCurrentText(theme[9])
            self.statusbar_font_comboBox.setCurrentText(theme[10])
            self.statusbar_color_comboBox.setCurrentText(theme[11])
            self.statusbar_font_color_comboBox.setCurrentText(theme[12])
            self.button_font_comboBox.setCurrentText(theme[13])
            self.button_color_comboBox.setCurrentText(theme[14])
            self.button_radius_comboBox_2.setCurrentText(str(theme[15]))
            self.button_font_color_comboBox_2.setCurrentText(theme[16])
            self.inputbox_font_comboBox.setCurrentText(theme[17])
            self.inputbox_color_comboBox_2.setCurrentText(theme[18])
            self.inputbox_radius_comboBox.setCurrentText(str(theme[19]))
            self.inputbox_font_color_comboBox.setCurrentText(theme[20])
            self.combobox_font_comboBox.setCurrentText(theme[21])
            self.combobox_color_comboBox.setCurrentText(theme[22])
            self.combobox_radius_comboBox.setCurrentText(str(theme[23]))
            self.combobox_font_color_comboBox.setCurrentText(theme[24])
            self.background_color_comboBox.setCurrentText(theme[25])

    def ok_apply_style(self):
        self.apply_style()
        self.dialog.close()

    def apply_active_theme(self):
        with self.connect:
            self.cursor.execute("SELECT * FROM settings WHERE active=1")
            theme = self.cursor.fetchone()
        if theme is None:
            self.main_window.setStyleSheet("background_color: white")
            self.menu_bar.setStyleSheet("background-color: rgb(216, 216, 216);")
            self.status_bar.setStyleSheet("background-color: rgb(216, 216, 216);")
            self.title_label.setStyleSheet("background-color: white")
        else:
            if theme[11] == "Light Grey":
                statusbar_color = "rgb(216, 216, 216)"
            else:
                statusbar_color = theme[11]
            if theme[8] == "Light Grey":
                menubar_color = "rgb(216, 216, 216)"
            else:
                menubar_color = theme[8]
            self.title_label.setStyleSheet(
                f"font-family: {theme[4]};\n"
                f"color: {theme[6]};\n"
                f"border-radius: {str(theme[15])}px;\n"
                f"background-color: {theme[5]};")
            self.menu_bar.setStyleSheet(f"font-family: {theme[7]};\n"
                                        f"color: {theme[9]};\n"
                                        f"background-color: {menubar_color};")
            self.status_bar.setStyleSheet(f"font-family: {theme[10]};\n"
                                          f"color: {theme[12]};\n"
                                          f"background-color: {statusbar_color};"
                                          )
            self.main_window.setStyleSheet(
                f"#centralwidget{{background-color: {theme[25]};}}\n"
                f"QLabel{{font-family: {theme[1]};\n"
                f"color: {theme[3]};\n"
                f"border-width: 2px;\n"
                f"border-radius: {str(theme[15])}px;\n"
                f"background-color: {theme[2]}}}\n"

                f"QLineEdit{{font-family: {theme[17]};\n"
                f"color: {theme[20]};\n"
                "border-width: 2px;\n"
                f"border-radius: {str(theme[19])}px;\n"
                f"background-color: {theme[18]}}}\n"

                f"QComboBox{{font-family: {theme[21]};\n"
                f"color: {theme[24]};\n"
                "border-width: 2px;\n"
                f"border-radius: {str(theme[23])}px;\n"
                f"background-color: {theme[22]}}}\n"

                f"QPushButton{{font-family: {theme[13]};\n"
                f"color: {theme[16]};\n"
                "border-width: 2px;\n"
                f"border-radius: {str(theme[15])}px;\n"
                f"background-color: {theme[14]}}}\n"

                f"QListWidget{{background-color: {theme[2]};\n"
                f"color: {theme[3]};\n"
                f"border-radius: {str(theme[15])}px;\n"
                f"font-family: {theme[1]}}};\n"
            )

    def apply_style(self):
        if self.saved_themes_comboBox.currentText() == "Default":
            self.main_window.setStyleSheet("background_color: white")
            self.menu_bar.setStyleSheet("background-color: rgb(216, 216, 216);")
            self.status_bar.setStyleSheet("background-color: rgb(216, 216, 216);")
            self.title_label.setStyleSheet("background-color: white")
        else:
            if self.statusbar_color_comboBox.currentText() == "Light Grey":
                statusbar_color = "rgb(216, 216, 216)"
            else:
                statusbar_color = self.statusbar_color_comboBox.currentText()
            if self.menubar_color_comboBox.currentText() == "Light Grey":
                menubar_color = "rgb(216, 216, 216)"
            else:
                menubar_color = self.menubar_color_comboBox.currentText()
            self.title_label.setStyleSheet(
                f"font-family: {self.title_font_comboBox.currentText()};\n"
                f"color: {self.title_font_color_comboBox.currentText()};\n"
                f"border-radius: {self.button_radius_comboBox_2.currentText()}px;\n"
                f"background-color: {self.title_color_comboBox.currentText()};")
            self.menu_bar.setStyleSheet(f"font-family: {self.menubar_font_comboBox.currentText()};\n"
                                        f"color: {self.menubar_font_color_comboBox.currentText()};\n"
                                        f"background-color: {menubar_color};")
            self.status_bar.setStyleSheet(f"font-family: {self.statusbar_font_comboBox.currentText()};\n"
                                          f"color: {self.statusbar_font_color_comboBox.currentText()};\n"
                                          f"background-color: {statusbar_color};"
                                          )
            self.main_window.setStyleSheet(
                f"#centralwidget{{background-color: {self.background_color_comboBox.currentText()};}}\n"
                f"QLabel{{font-family: {self.labels_font_comboBox.currentText()};\n"
                f"color: {self.labels_font_color_comboBox.currentText()};\n"
                f"border-width: 2px;\n"
                f"border-radius: {self.button_radius_comboBox_2.currentText()}px;\n"
                f"background-color: {self.labels_color_comboBox.currentText()}}}\n"

                f"QLineEdit{{font-family: {self.inputbox_font_comboBox.currentText()};\n"
                f"color: {self.inputbox_font_color_comboBox.currentText()};\n"
                "border-width: 2px;\n"
                f"border-radius: {self.inputbox_radius_comboBox.currentText()}px;\n"
                f"background-color: {self.inputbox_color_comboBox_2.currentText()}}}\n"

                f"QComboBox{{font-family: {self.combobox_font_comboBox.currentText()};\n"
                f"color: {self.combobox_font_color_comboBox.currentText()};\n"
                "border-width: 2px;\n"
                f"border-radius: {self.combobox_radius_comboBox.currentText()}px;\n"
                f"background-color: {self.combobox_color_comboBox.currentText()}}}\n"

                f"QPushButton{{font-family: {self.button_font_comboBox.currentText()};\n"
                f"color: {self.button_font_color_comboBox_2.currentText()};\n"
                "border-width: 2px;\n"
                f"border-radius: {self.button_radius_comboBox_2.currentText()}px;\n"
                f"background-color: {self.button_color_comboBox.currentText()}}}\n"

                f"QListWidget{{background-color: {self.labels_color_comboBox.currentText()};\n"
                f"color: {self.labels_font_color_comboBox.currentText()};\n"
                f"border-radius: {self.combobox_radius_comboBox.currentText()}px;\n"
                f"font-family: {self.combobox_font_comboBox.currentText()}}};\n"
            )

    def save_style(self):
        if self.theme_name_lineEdit.text() == '':
            error_box("You must specify a name for your theme.")
            return 0
        with self.connect:
            self.cursor.execute("SELECT name FROM settings")
            themes = [theme[0] for theme in self.cursor.fetchall()]
            if self.theme_name_lineEdit.text() in themes:
                error_box("There is already a theme by that name.")
                return 0
            self.cursor.execute("""INSERT INTO settings (name,
                                                       label_font,
                                                       label_color,
                                                       label_font_color,
                                                       title_font,
                                                       title_color,
                                                       title_font_color,
                                                       menubar_font,
                                                       menubar_color,
                                                       menubar_font_color,
                                                       statusbar_font,
                                                       statusbar_color,
                                                       statusbar_font_color,
                                                       button_font,
                                                       button_color,
                                                       button_radius,
                                                       button_font_color,
                                                       inputbox_font,
                                                       inputbox_color,
                                                       inputbox_radius,
                                                       inputbox_font_color,
                                                       combobox_font,
                                                       combobox_color,
                                                       combobox_radius,
                                                       combobox_font_color,
                                                       bg_color,
                                                       active)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,
                                                                        ?,?,?)""",
                                (self.theme_name_lineEdit.text(),
                                 self.labels_font_comboBox.currentText(),
                                 self.labels_color_comboBox.currentText(),
                                 self.labels_font_color_comboBox.currentText(),
                                 self.title_font_comboBox.currentText(),
                                 self.title_color_comboBox.currentText(),
                                 self.title_font_color_comboBox.currentText(),
                                 self.menubar_font_comboBox.currentText(),
                                 self.menubar_color_comboBox.currentText(),
                                 self.menubar_font_color_comboBox.currentText(),
                                 self.statusbar_font_comboBox.currentText(),
                                 self.statusbar_color_comboBox.currentText(),
                                 self.statusbar_font_color_comboBox.currentText(),
                                 self.button_font_comboBox.currentText(),
                                 self.button_color_comboBox.currentText(),
                                 self.button_radius_comboBox_2.currentText(),
                                 self.button_font_color_comboBox_2.currentText(),
                                 self.inputbox_font_comboBox.currentText(),
                                 self.inputbox_color_comboBox_2.currentText(),
                                 self.inputbox_radius_comboBox.currentText(),
                                 self.inputbox_font_color_comboBox.currentText(),
                                 self.combobox_font_comboBox.currentText(),
                                 self.combobox_color_comboBox.currentText(),
                                 self.combobox_radius_comboBox.currentText(),
                                 self.combobox_font_color_comboBox.currentText(),
                                 self.background_color_comboBox.currentText(),
                                 0
                                 ))
        self.refresh_themes()
